NIFTY:
  lot_size: 65
  num_lots: 1
  max_daily_loss: 3500
  sl_points: 15
  target_points: 45
  slippage_buffer: 0.5
  profit_lock_threshold: 3000
  profit_protection:
    enable_scalp_mode: true
    sl_points: 6
    target_points: 7
    drawdown_limit: 1000
  trailing_sl_tiers:
    - activation: 6
      fix_sl: -12
    - activation: 8
      fix_sl: -8
    - activation: 10
      fix_sl: -2
    - activation: 13
      distance: 6
    - activation: 20
      trail_type: candle_open
      min_distance: 3
  ce_setup_allowed: false
  pe_setup_allowed: true
  current_ce_setup_discard: false
  current_pe_setup_discard: false
  allowed_trading_hours:
    9: true   # 09:15 - 10:15
    10: true  # 10:15 - 11:15
    11: true  # 11:15 - 12:15
    12: true  # 12:15 - 13:15
    13: true  # 13:15 - 14:15
    14: true  # 14:15 - 15:15

SENSEX:
  lot_size: 20
  num_lots: 1
  max_daily_loss: 3500
  sl_points: 50
  target_points: 400
  slippage_buffer: 4.0
  profit_lock_threshold: 3000
  profit_protection:
    enable_scalp_mode: false
    sl_points: 20
    target_points: 25
    drawdown_limit: 1000
  trailing_sl_tiers:
    - activation: 10
      fix_sl: -40
    - activation: 20
      fix_sl: -30
    - activation: 25
      fix_sl: -20
    - activation: 40
      fix_sl: 0
    - activation: 50
  #    distance: 20
      trail_type: candle_open
      min_distance: 20
      fallback_sl_buffer: 20
  ce_setup_allowed: true
  pe_setup_allowed: true
  current_ce_setup_discard: false
  current_pe_setup_discard: false
  allowed_trading_hours:
    9: true
    10: true
    11: true
    12: true
    13: true
    14: true