NIFTY:
  lot_size: 65
  num_lots: 1
  sl_points: 10
  target_points: 15
  trailing_activation_points: 12
  trailing_distance_points: 10
  ce_setup_allowed: true
  pe_setup_allowed: true
  current_ce_setup_discard: false
  current_pe_setup_discard: false

SENSEX:
  lot_size: 20
  num_lots: 1
  sl_points: 10
  target_points: 15
  trailing_activation_points: 10
  trailing_distance_points: 10
  ce_setup_allowed: true
  pe_setup_allowed: true
  current_ce_setup_discard: false
  current_pe_setup_discard: false